name: Python Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install UV
      uses: astral-sh/setup-uv@v1
      
    - name: Install dependencies
      run: |
        uv sync
        
    - name: Run basic tests
      run: |
        uv run test_server.py
        
    - name: Test server functionality
      run: |
        # Start server in background
        timeout 30s uv run mcpserver/server.py &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 10
        
        # Test if server is responding
        curl -f http://localhost:8000/sse || echo "Server not responding yet"
        
        # Run test
        uv run test_server.py
        
        # Clean up
        kill $SERVER_PID 2>/dev/null || true
        
    - name: Test MCP tools
      run: |
        # Test if tools can be imported
        python -c "
        import sys
        sys.path.append('mcpserver')
        from server import get_forecast, get_result
        print('✅ MCP tools imported successfully')
        "
        
    - name: Check Python syntax
      run: |
        python -m py_compile mcpserver/server.py
        python -m py_compile mcpserver/client-sse.py
        python -m py_compile test_server.py
        echo "✅ All Python files compile successfully"

